Create count_sort.go
TheAlgorithms/Go pull request #108
Opened 2020-03-07 14:40 UTC by aakashdinkar

2020-09-28 12:53 UTC, nomisrevol requested changes

2020-09-28 12:53 UTC, nomisrevol commented on sorts/count_sort.go
> + 	for(i<n){
Please re-format the code with `golint`. I see that all your loop can follow the format
```{go}
for i := initialValue; i < condition; i++ {
  ... some part of code
}
```
Please refactor all your code as the template above.

2020-09-28 12:53 UTC, nomisrevol commented on sorts/count_sort.go
> + 	count:=make([]int, max-0+1) 	//initializing count array to zero
Why `max-0+1`? Why not simply `max - 1`?

2021-09-10 21:18 UTC, tjgurwara99 commented
Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

2021-09-24 05:59 UTC, closed without merging