Ternary Search Algorithm Added
TheAlgorithms/Go pull request #131
Opened 2020-06-04 17:04 UTC by MarcosVillacanas

Ternary Search was missing, now is available. 
The code has a main function to be used as a test, for example, in https://play.golang.org/. 
I have added some comments to make it easier to understand.

2020-06-09 22:31 UTC, MarcosVillacanas commented on searches/ternary_search.go
> +	} else if target == array[mid1] {
Solved, thank you

2020-06-09 22:31 UTC, MarcosVillacanas commented on searches/ternary_search.go
> +	    Worst-case performance	Θ(log3(N))
Solved on new commit, thank you

2020-06-16 17:37 UTC, luislizarraga commented
Looks good, great work!

2020-10-01 11:13 UTC, nomisrevol requested changes

2020-10-01 11:13 UTC, nomisrevol commented on searches/ternary_search.go
> +func main() {
Remove `main` function and add a new test file instead.

2021-09-10 21:22 UTC, tjgurwara99 commented
Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

2021-09-24 05:59 UTC, closed without merging