Refactor fastExponent.go
TheAlgorithms/Go pull request #173
Opened 2020-09-14 05:15 UTC by vedantmamgain

refactor: condensed the function and added comments for the steps

2020-09-29 05:38 UTC, nomisrevol requested changes

2020-09-29 05:38 UTC, nomisrevol commented on math/fastExponent.go
> +	res := 1 // res is the final result
Remove unnecessary comments. Please add more references to the implementation (describe how it work, or refer to other document explain how it work. Naming things meaningful also. 

Could you remove the main function and write some testcases for this implementation?

2020-09-29 13:52 UTC, vedantmamgain reviewed
Check it now..

2020-09-29 14:12 UTC, nomisrevol commented
You're giving us 3 implementations of the same algorithm. It is really good, but it will be better if in the pull request, you can show us the benchmark between these 3 implementations. Or maybe describe pros and cons of each implementation in PR. Thank you.

2020-09-29 17:20 UTC, vedantmamgain reviewed
Have added the benchmarking results of all the three types of implementations of the algorithm.

2020-09-30 09:21 UTC, nomisrevol commented
LGTM!

2020-09-30 09:22 UTC, nomisrevol approved these changes

2020-09-30 17:04 UTC, vedantmamgain commented
Merge? Or is there anything left?

2020-10-01 05:37 UTC, nomisrevol commented
What's `primalityTest.go`? If it is an implementation for another algorithm, please cherry-pick that commit to other branch and create another pull request. Reset the HEAD to commit `e0216bb` then I will merge it. Sorry for the late response.

2020-10-01 07:02 UTC, vedantmamgain commented
Let me make a fresh pr for both of them seperately.

2020-10-01 07:04 UTC, closed without merging