Create primalityTest.go
TheAlgorithms/Go pull request #179
Opened 2020-10-01 07:09 UTC by vedantmamgain

2020-10-01 11:20 UTC, nomisrevol requested changes

2020-10-01 11:20 UTC, nomisrevol commented on math/primalityTest.go
> +package main
`primalityTest` is not a good name for this prime checking implementation. Please rename it to `prime_check.go` and implement a test file also.

2020-10-01 11:20 UTC, nomisrevol commented on math/primalityTest.go
> +	if n==1{
It is more strict with condition `n < 2`.

2020-10-01 11:20 UTC, nomisrevol commented on math/primalityTest.go
> +	if n==1{
`n < 2` also.

2020-10-01 11:20 UTC, nomisrevol commented on math/primalityTest.go
> +	for i:=2;i*i<=n;i++ {
What will happen if `i * i` overflow?

2020-10-02 10:48 UTC, vedantmamgain commented
Check it now. @nomisrevol

2020-10-02 12:33 UTC, nomisrevol commented
@vedantmamgain How about test file?

2020-10-02 13:45 UTC, vedantmamgain commented
@nomisrevol  Added test file for both the approaches.

2020-10-04 05:03 UTC, vedantmamgain commented
@nomisrevol Is there anything that is remaining?

2020-10-04 14:12 UTC, merged

2020-10-04 14:12 UTC, nomisrevol commented
@vedantmamgain It's ok for now. Sorry for the late reply. I will merge it, fyi.