add min, max, range, distances
TheAlgorithms/Go pull request #196
Opened 2020-10-06 18:52 UTC by SotirisGP

added min, min distance from 0, max, max distance from 0 and range on a list of numbers

2020-10-07 05:16 UTC, nomisrevol requested changes
Overall, you are naming things not really good, trying to see this doc as reference: https://github.com/unknwon/go-code-convention/blob/master/en-US/naming_rules.md#:~:text=Variable%20name%20is%20generally%20using,e.g.%20APIClient%20%2C%20repoID%20%2C%20UserID%20.

Also, find a more meaningful variable name for your variables.

2020-10-07 05:16 UTC, nomisrevol commented on math/find_min_max.go
> +func abs(a float64) float64 {
Please reuse the existence function.

2020-10-07 05:16 UTC, nomisrevol commented on math/find_min_max.go
> +func main() {
Remove the `main` function and write the test file instead.

2020-10-07 05:16 UTC, nomisrevol commented on math/find_min_max.go
> +func maxDist(numbers []float64) float64 {
Should rename to `maxDistToZero`, I think it is more meaningful.

2021-09-10 21:45 UTC, tjgurwara99 commented
Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

2021-09-24 05:58 UTC, closed without merging