Patch 1
TheAlgorithms/Go pull request #239
Opened 2020-10-19 17:11 UTC by addy1997

created a code for catalan number

2020-10-19 19:29 UTC, Mystigan requested changes
- Please ensure the program is logically correct. Also add proper unit tests. This ensures correctness to a great extent.
- Remove main function.
- Refactor with proper package and function names.
- Why did you delete the `sorts_test.go` file? Please add it back, it is an important part of the sorts package.

2020-10-20 03:00 UTC, addy1997 commented
@Mystigan I have included the test and renamed the functions [#239 ]

2020-10-22 17:16 UTC, Mystigan requested changes
- Look at inline comments.
- Add the sorts_test file back. Why did you delete it?
- Remove extra whitespaces.

2020-10-22 17:16 UTC, Mystigan commented on other/catalan.go
> +package testing101
When I said proper package names, I meant it in the context of the project. The Go way to do it is that the package name is the folder in which the file is kept.

2020-10-22 17:16 UTC, Mystigan commented on other/catalan_test.go
> +
- Add more tests.
- Use table driven tests.
- Enclose test cases in t.Run().

2021-09-11 11:02 UTC, tjgurwara99 commented
Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

2021-09-11 11:25 UTC, addy1997 commented
> Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

Wow! that's a quick response. 
Add this point to your guidelines
*Respond to the PR before it becomes too stale*

2021-09-11 11:25 UTC, closed without merging

2021-09-11 11:27 UTC, tjgurwara99 commented
Unfortunately, I became a maintainer recently so your point is valid but I'm not at fault. Hope you enjoy the rest of your day.

2021-09-11 11:35 UTC, siriak commented
@addy1997 I'm sorry that it took you so long to get meaningful feedback, we're working on that project in our spare time and cannot allocate more resources to that activity. We'll do our best to review new contributions as soon as possible in the future. Have a good day!