Add moser-de bruijin sequence
TheAlgorithms/Go pull request #255
Opened 2020-11-06 05:46 UTC by cp-sumi-k

2020-11-06 14:18 UTC, Navid2zp requested changes
You need to add the tests too. Check other algorithms for example.

2020-11-06 14:18 UTC, Navid2zp commented on math/moserdebruijnsequence/sequence.go
> +// adding up the distinct powers of the number 4 (For example 1, 4, 16, 64, etc).
You should probably add the Wikipedia URL:
https://en.wikipedia.org/wiki/Moser%E2%80%93de_Bruijn_sequence

2020-11-06 14:18 UTC, Navid2zp commented on math/moserdebruijnsequence/sequence.go
> +func main() {
Also, you should remove the main function.
You can change your `getSequenceNumber` function to `MoserDeBruijnSequence` instead and return the final result.

2020-11-07 04:06 UTC, cp-sumi-k commented
Changes Done @Navid2zp. Please review it.

2020-11-07 15:23 UTC, Navid2zp commented
> Changes Done @Navid2zp. Please review it.

I'm not a maintainer but looks good to me. Wait for one of the maintainers to check.
Just wanted to point out the simple problems so you can fix it before one of the maintainers check the PR since it usually takes a while.

2020-11-07 15:23 UTC, Navid2zp submitted a review, later dismissed

2021-08-21 06:06 UTC, iamrajiv submitted a review, later dismissed

2021-08-25 04:54 UTC, siriak approved these changes
LGTM except for 1 comment below. Please bring the branch up to date so that I could merge it in.

2021-08-25 04:54 UTC, siriak commented on math/moserdebruijnsequence/sequence_test.go
> +	{"first 10 terms", 10, []int{0, 1, 4, 5, 16, 17, 20, 21, 64, 65}},
No need to test the first 0, 5, and 10 terms if you're testing the first 15 terms too

2021-08-31 04:59 UTC, siriak approved these changes

2021-08-31 04:59 UTC, merged