doc: fix: Fix links in README.md
TheAlgorithms/Go pull request #345
Opened 2021-09-10 18:52 UTC by oskarwojciski

Fix links - connected to issue #344

2021-09-10 20:16 UTC, tjgurwara99 requested changes
Thanks for doing this. I have added some suggestions for changes. I think it is best to keep directing people to `*.go` files instead of directories as directories can be overwhelming for beginners. Most modern IDE's can go to the definition of functions when you `ctrl/cmd + click` on them so arguably it makes it easier to do that from inside the file.

Also could I kindly ask you to take a look at some other listings here that you have not edited but are directing to a directory instead of `*.go` files.

2021-09-10 20:16 UTC, tjgurwara99 commented on README.md
> +* [Pythagoras](./math/pythagoras)
```suggestion
* [Gcd](./math/gcd)
    * [Extended](./math/gcd/extended.go)
    * [Recursive](./math/gcd/gcd.go)
    * [Iterative](./math/gcd/gcditerative.go)
* [Lcm](./math/lcm/lcm.go)
* [Max](./math/max/max.go)
* [Modular](./math/modular)
    * [Exponentiation](./math/max/max.go)
    * [Inverse](./math/modular/inverse.go) 
* [Moser-de Bruijn sequence](./math/moserdebruijnsequence/sequence.go)
* [Permutation](./math/permutation/heaps.go)
* [Power](./math/power/fastexponent.go)
* [Prime](./math/prime)
    * [Miller Rabin Primality Test](./math/prime/millerrabinprimalitytest.go)
    * [Naive and Pair Approach](./math/prime/primecheck.go)
    * [Sieve](./math/prime/sieve.go)
* [Pythagoras](./math/pythagoras/pythagoras.go)
```

2021-09-10 20:16 UTC, tjgurwara99 commented on README.md
> +* [Password Generator](./other/password)
```suggestion
* [Max Subarray Sum](./other/maxsubarraysum/maxsubarraysum.go)
* [Nested Brackets](./other/nested/nestedbrackets.go)
* [Password Generator](./other/password/generator.go)
```

2021-09-10 20:16 UTC, tjgurwara99 commented on README.md
> +    * [Kmp](./strings/kmp)
```suggestion
    * [Bom](./strings/bom/bom.go)
    * [Horspool](./strings/horspool/horspool.go)
    * [Kmp](./strings/kmp/kmp.go)
```

2021-09-10 20:45 UTC, tjgurwara99 commented
Re-request review by clicking there when you think this PR ready to be reviewed😄

<img width="443" alt="Screenshot 2021-09-10 at 21 44 59" src="https://user-images.githubusercontent.com/21105489/132915573-c7e4b9b9-ef39-4970-b338-b8597a8b19a2.png">

2021-09-10 20:58 UTC, tjgurwara99 approved these changes

2021-09-10 20:58 UTC, tjgurwara99 approved these changes
LGTM. Thanks!

2021-09-11 11:23 UTC, siriak approved these changes
LGTM

2021-09-11 11:24 UTC, merged