Recursion to find the exponent
TheAlgorithms/Go pull request #368
Opened 2021-10-02 11:19 UTC by thearkamitra

2021-10-02 16:31 UTC, tjgurwara99 requested changes
Please read our contribution guidelines before opening a PR.

2021-10-02 16:32 UTC, tjgurwara99 requested changes

2021-10-02 16:32 UTC, tjgurwara99 commented on recursion/exponent.go
> +package main
Specifically the part where it says the functions should be self contained and not in a main package.

2021-10-02 16:37 UTC, tjgurwara99 requested changes

2021-10-02 16:37 UTC, tjgurwara99 commented on recursion/exponent.go
> +package main
Change the package name to something meaningful and not main

2021-10-02 16:37 UTC, tjgurwara99 commented on recursion/exponent.go
> +func exponentialrecursion(x int, p int) int {
Export this function and write a test for this

2021-10-05 17:26 UTC, siriak approved these changes
Agree with previous comments, but apart from that looks good

2021-11-15 00:06 UTC, closed without merging