Comb Sort algorithm implementation
TheAlgorithms/Go pull request #407
Opened 2021-10-21 06:15 UTC by kavithajm

![image](https://user-images.githubusercontent.com/91771245/138221735-28f54b8a-467b-425f-8ffe-aa7a4655c020.png)

2021-10-21 10:26 UTC, kavithajm commented
Formatted the code using gofmt.

2021-11-08 17:31 UTC, tjgurwara99 requested changes
Please fix the errors in the test file.

2021-11-08 17:31 UTC, tjgurwara99 commented on sort/sorts_test.go
> +	testFramework(t, combSort)
```suggestion
	testFramework(t, Comb)
```

2021-11-08 17:31 UTC, tjgurwara99 commented on sort/sorts_test.go
> +	benchmarkFramework(b, combSort)
```suggestion
	benchmarkFramework(b, Comb)
```

2021-11-10 12:51 UTC, tjgurwara99 approved these changes

2021-11-10 13:14 UTC, raklaptudirm approved these changes

2021-11-10 13:38 UTC, tjgurwara99 approved these changes

2021-11-10 14:40 UTC, raklaptudirm commented
@tjgurwara99 The workflow seems to be frozen.

2021-11-10 16:44 UTC, tjgurwara99 commented
> @tjgurwara99 The workflow seems to be frozen.

@raklaptudirm Yeah, it keeps happening when we update the branch. I can't seem to find out the reason for this. It gets fixed when there is more activity happening on the PR like commits etc but this freeze should not really happen. I will log a bug to the GitHub/runner repo to see if they can see where this issue is coming from, like If it is because of the changes I made recently or is its something else.

2021-11-11 18:48 UTC, siriak approved these changes

2021-11-11 18:52 UTC, merged