Feat: bits counter
TheAlgorithms/Go pull request #439
Opened 2021-11-16 07:36 UTC by i-redbyte

bits counter function

2021-11-16 09:04 UTC, raklaptudirm approved these changes

2021-11-16 20:14 UTC, siriak requested changes

2021-11-16 20:14 UTC, siriak commented on math/binary/bitcounter_test.go
> +		{"Number of bits in a number 255", 8, 1},
Please update descriptions

2021-11-17 07:15 UTC, i-redbyte commented on math/binary/bitcounter_test.go
> +		{"Number of bits in a number 255", 8, 1},
Done

2021-11-17 08:24 UTC, siriak approved these changes

2021-11-17 08:48 UTC, raklaptudirm approved these changes

2021-11-17 08:55 UTC, merged