Find min
TheAlgorithms/Go pull request #45
Opened 2019-03-06 15:21 UTC by BooGluten

A function that finds the minimum value in a list.

2019-10-12 12:31 UTC, katkad commented on findmin.go
> +            smallest = x
Hi. No need to assign new smallest value, if x  == smallest.

x < smallest
will do

2019-10-12 12:35 UTC, katkad commented on findmin.go
> +        var x = in[i]
Hi. You can start from in[1], because in[0] is already in smallest variable. You do not need to compare in[0] and in[0].

2020-10-14 03:02 UTC, Mystigan requested changes
Hi,
Please work on the changes suggested by @katkad . Other than that:
- Please move this file into either `math` or `other` folder`. Rename the package accordingly.
- Remove the main function. Add a test file.

2021-09-10 21:08 UTC, tjgurwara99 commented
Most comments requesting changes are still valid, even now. Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

2021-09-24 06:00 UTC, closed without merging