added recursive method for palindrome
TheAlgorithms/Go pull request #455
Opened 2021-12-24 07:52 UTC by nischal20

2021-12-24 20:09 UTC, siriak approved these changes

2021-12-26 15:33 UTC, tjgurwara99 requested changes

2021-12-26 15:33 UTC, tjgurwara99 commented on strings/palindrome/ispalindrome.go
> +}
```suggestion
func IsPalindromeRecursiveHelper(runes []rune, start int64, end int64) bool {
	if start >= end {
		return true
	}
	if string(runes[start]) != string(runes[end-1]) {
		return false
	}
	start = start + 1
	end = end - 1

	return IsPalindromeRecursiveHelper(runes, start, end)
}
```

2021-12-26 15:35 UTC, tjgurwara99 commented on strings/palindrome/ispalindrome.go
> +}
If you know the condition to return then return early.

2021-12-26 18:21 UTC, tjgurwara99 requested changes

2021-12-26 18:21 UTC, tjgurwara99 commented on strings/palindrome/ispalindrome.go
> +	if string(runes[start]) != string(runes[end-1]) {
The string conversion is redundant here

2021-12-26 18:28 UTC, nischal20 commented on strings/palindrome/ispalindrome.go
> +	if string(runes[start]) != string(runes[end-1]) {
removed string conversion

2021-12-27 01:44 UTC, tjgurwara99 requested changes
Make the helper an unexported function. That is not useful/needed outside this package.

2021-12-27 01:44 UTC, tjgurwara99 commented on strings/palindrome/ispalindrome.go
> +func IsPalindromeRecursiveHelper(runes []rune, start int64, end int64) bool {
```suggestion
func isPalindromeRecursiveHelper(runes []rune, start int64, end int64) bool {
```

2021-12-27 18:12 UTC, tjgurwara99 submitted a review, later dismissed
LGTM

2021-12-28 19:27 UTC, siriak approved these changes

2021-12-28 19:56 UTC, tjgurwara99 approved these changes

2021-12-28 19:56 UTC, merged