Remove redundant section with broken link (fixes #498)
TheAlgorithms/Go pull request #500
Opened 2022-04-23 19:37 UTC by siriak

2022-04-24 07:16 UTC, raklaptudirm requested changes

2022-04-24 07:16 UTC, raklaptudirm commented on CONTRIBUTING.md
> -**Please check the [reviewer code](https://github.com/TheAlgorithms/Go/blob/master/DIRECTORY.md) file for maintainers and reviewers.**
Instead of removing this section, point it to the [`CODEOWNERS`](https://github.com/TheAlgorithms/Go/blob/master/.github/CODEOWNERS) file.

2022-04-24 08:48 UTC, raklaptudirm submitted a review, later dismissed

2022-04-24 08:48 UTC, raklaptudirm commented on CONTRIBUTING.md
> +Please check the [reviewer code](https://github.com/TheAlgorithms/Go/blob/master/.github/CODEOWNERS) file for maintainers and reviewers.
```suggestion
Please check the [`CODEOWNERS`](https://github.com/TheAlgorithms/Go/blob/master/.github/CODEOWNERS) file for a list of repository maintainers.
```

2022-04-24 08:48 UTC, raklaptudirm commented on CONTRIBUTING.md
>  ### Maintainer/reviewer
```suggestion
### Maintainers
```

2022-04-25 14:41 UTC, raklaptudirm submitted a review, later dismissed

2022-04-26 20:49 UTC, siriak commented
I've also fixed a formatting issue

2022-04-27 09:06 UTC, raklaptudirm commented
@siriak That issue is separate from this pull request, so no need to fix it here. See #501

2022-04-27 13:59 UTC, raklaptudirm approved these changes

2022-04-28 13:27 UTC, tjgurwara99 approved these changes

2022-04-28 13:27 UTC, merged