add patience sorting algorithm
TheAlgorithms/Go pull request #517
Opened 2022-08-04 00:26 UTC by guuzaa

feat: add patience sorting algorithm

2022-08-04 08:34 UTC, tjgurwara99 requested changes

2022-08-04 08:34 UTC, tjgurwara99 commented on sort/patiencesort.go
> +			mid := left + (right-left)>>1
```suggestion
			mid := (left + (right-left))>>1
```

might make it more clear what you're trying to do.

But I also suggest to keep this simple, no need for fancy bit shifting when we already know that the compiler is quick enough in division by 2. So
```suggestion
			mid := (left + (right-left))/2
```
might be more suitable.

2022-08-04 08:34 UTC, tjgurwara99 commented on sort/patiencesort.go
> +			}
Flip this into a guard statement maybe...

```suggestion
			if minV <= piles[i][len(piles[i])-1] {
				continue
			}
			// Update minV
			minV = piles[i][len(piles[i])-1]
			// Update index
			minId = i
```

2022-08-04 08:34 UTC, tjgurwara99 commented on sort/patiencesort.go
> +		minId := 0
whenever you're using `Id` in Go, you should use it with `ID` instead of capitalising just `I`, so in this case
```suggestion
		minID := 0
```

2022-08-04 08:34 UTC, tjgurwara99 commented on sort/patiencesort.go
> +	// util all piles are empty
Not necessary to explain the code. Your code is the explanation of what is happening, comment should be used only when you have to explain why you're doing something that might not be quite straight forward.

Comments should explain "why" not "what" (IMO)

2022-08-04 08:34 UTC, tjgurwara99 commented on sort/patiencesort.go
> +				// Update minV
Again, no need for these kinds of comments.

2022-08-04 08:34 UTC, tjgurwara99 commented on sort/patiencesort.go
> +	// Traverse the given array
This comment doesn't provide value to anyone reading the code.

2022-08-04 16:20 UTC, siriak submitted a review, later dismissed
The code looks good, but a formatting check is failing

2022-08-05 09:42 UTC, tjgurwara99 commented
Please run `gofmt` on your code

2022-08-05 10:39 UTC, guuzaa commented
Sorry, I ran `gofmt` on my code. I don't know why this error happened.
I will double check it as soon as possible.

2022-08-05 10:53 UTC, guuzaa commented
It is a little weird. These formatting errors occur on the files I didn't change.

2022-08-05 13:17 UTC, guuzaa commented
Hi @tjgurwara99 , I have run `golangci-lint` on my code. There are indeed some formatting errors. Then, I try to run `gofmt -w` on these files. However, there is no change. Due to these files are not written by me, I cannot change it manually. As a reult, I'm writing this comment to ask for your help.

The following is my machine :
OS `Ubuntu 20.04.3 LTS`
Go `1.18.3`
golangcli-lint  `1.48.0 built from 2d8fea81 on 2022-08-04T18:44:38Z`

2022-08-05 13:48 UTC, guuzaa commented
I checked these files again. There isn't a leading space in some comments. Does it matter?

2022-08-05 14:22 UTC, guuzaa commented
I might find the reason.
The[ last PR](https://github.com/TheAlgorithms/Go/pull/514) tested  with `golangci-lint` 1.47.
![image](https://user-images.githubusercontent.com/67539676/183095585-8696b893-2f78-481e-83e4-60788ed678b5.png)
Recently `golangci-lint`  was upgraded to 1.48, and the old code no longer pass the formatting check.
![image](https://user-images.githubusercontent.com/67539676/183095693-0f7ca63a-40a1-4478-add2-d994e90d70a3.png)

2022-08-05 17:24 UTC, tjgurwara99 commented
> I checked these files again. There isn't a leading space in some comments. Does it matter?

If it did, it wouldn't have passed earlier either. I also tried to look into it and couldn't wrap my head around it. Thanks for pointing out the version difference, I was going to inspect that too. I will take a look at `golangci-lint` change logs  and see what they changed. Might be related to the new Go 1.19 and the new doc styling.

In the meantime, if you'd like to merge this PR for now, I don't see any harm there since the issue is not related to your changes. cc @siriak @raklaptudirm what do you think? If you don't mind waiting however, I would prefer to get this sorted and can add changes to your PR directly.

2022-08-05 17:27 UTC, raklaptudirm commented
If the required changes are unrelated to this pr, we should merge this and make those changes ourselves imo.

2022-08-05 17:28 UTC, siriak commented
Agree with @raklaptudirm, but fixing them here also works if done quickly

2022-08-05 17:45 UTC, tjgurwara99 commented
Ok, I looked over it and this is a bigger issue on the `golangci-lint` side. It seems that the issue is essentially related to the `//` and `// ` and other space formatting issues. There is a newly opened [issue](https://github.com/golangci/golangci-lint/issues/3069) on `golangci-lint` repo, which is unlikely to be quickly fixed so we can merge this PR now I guess.

2022-08-05 18:08 UTC, tjgurwara99 commented
#518 fixes the issues cc @siriak @raklaptudirm @yanglbme - try to merge that before merging this 😄 

Also, the issue was indeed related to the spacing. The changes are mostly adding space or removing tabs or both in some cases. It seems that the golangci-lint 1.48 made it a bit stricter, which is quite good but not backwards compatible since this is not enforced at the `gofmt` level.

2022-08-06 04:30 UTC, raklaptudirm approved these changes

2022-08-06 05:13 UTC, guuzaa commented
I think I should merge the master first and push the merged code to this PR.

2022-08-06 11:23 UTC, tjgurwara99 approved these changes

2022-08-06 11:23 UTC, merged