Add tangent
TheAlgorithms/Go pull request #524
Opened 2022-08-09 05:35 UTC by Codesuckmehard

To calculate the radians of tangent

2022-08-09 13:46 UTC, tjgurwara99 requested changes

2022-08-09 13:46 UTC, tjgurwara99 commented on math/tan.go
> +	return Cot((math.Pi / 2) - x)
I don't think we have `Cot` defined, do we?

Anyways, we have `Sin` and `Cos` defined so why not use the `Sin/Cos`?

2022-08-09 13:48 UTC, raklaptudirm commented
IMO, this algorithm is too trivial.

2022-08-09 13:56 UTC, tjgurwara99 commented
> IMO, this algorithm is too trivial.

Depends on what you mean by trivial. If you look at our [Cos](https://github.com/TheAlgorithms/Go/blob/feb2246c4605f9c9b4e00a491b2930524bbda2be/math/cos.go#L10) then I don't think composing these algorithms together to make new ones is trivial. If this is trivial, then our [Sin](https://github.com/TheAlgorithms/Go/blob/feb2246c4605f9c9b4e00a491b2930524bbda2be/math/sin.go#L9) is also quite trivial.

2022-08-10 18:27 UTC, raklaptudirm requested changes
Format your code with <samp>gofmt</samp>.

2022-09-18 00:13 UTC, closed without merging