Added a useful resource
TheAlgorithms/Go pull request #525
Opened 2022-08-16 14:39 UTC by Vaishnaviamirayada

Have added a useful resource about the linked list in a data structure from the scaler topics.

2022-08-16 15:15 UTC, tjgurwara99 requested changes
Consider the following suggestion

2022-08-16 15:15 UTC, tjgurwara99 commented on structure/linkedlist/Readme.md
> +[Linked list is a data structure](https://www.scaler.com/topics/linked-list/) that is a linear chain of data elements whose order is not given by their phyisical placement in memory. This structure i
I think just wrapping the `Linked list` into a link is better than the whole thing.

```suggestion
[Linked list](https://www.scaler.com/topics/linked-list/) is a data structure that is a linear chain of data elements whose order is not given by their phyisical placement in memory. This structure is built up of nodes which point to the element ahead or behind this particular node (depending on the type of Linked List).
```

2022-08-16 15:18 UTC, tjgurwara99 commented on structure/linkedlist/Readme.md
> +[Linked list is a data structure](https://www.scaler.com/topics/linked-list/) that is a linear chain of data elements whose order is not given by their phyisical placement in memory. This structure i
But overall I would also recommend looking over the code to see the documentation code. There is an automated doc generator that we have in this repository that generates the documentation for all the implementations in the repository. I believe they are more representative and would also hold the most up to date information. 🙂

2022-08-17 14:57 UTC, tjgurwara99 approved these changes

2022-08-20 20:28 UTC, siriak approved these changes

2022-08-20 20:28 UTC, merged