algorithm: Liouville lambda function
TheAlgorithms/Go pull request #540
Opened 2022-09-16 02:21 UTC by itsAkshayDubey

This PR contains commits related to the implementation of [Liouville lambda function](https://en.wikipedia.org/wiki/Liouville_function). Kindly have a look.

2022-09-16 09:16 UTC, tjgurwara99 requested changes

2022-09-16 09:16 UTC, tjgurwara99 commented on math/liouville.go
> +func Lambda(n int) (int, error) {
There are many things in CS that are called `Lambda`. I think you should make this `LiouvilleLambda` or `LiouvilleFunc` to make it easier to not get this confused with other `Lambda`s.

2022-09-16 09:16 UTC, tjgurwara99 commented on math/liouville.go
> +	return -1, nil
When you see more than 2 `if` statements, consider whether you can use a `switch` case instead. This is mostly styling preference and therefore not blocking.

2022-09-20 09:34 UTC, tjgurwara99 requested changes

2022-09-20 09:34 UTC, tjgurwara99 commented on math/liouville.go
> +var ErrNonZeroArgsOnly error = errors.New("arguments must be greater than zero")
The name is not correct. The name of the error implies that the arguments also accepts negative number but the comment inside the error indicates that only positive numbers are allowed.

2022-09-20 11:19 UTC, tjgurwara99 approved these changes

2022-09-20 18:44 UTC, siriak approved these changes
Looks good, thanks!

2022-09-20 18:44 UTC, merged