feat: add lerp
TheAlgorithms/Go pull request #545
Opened 2022-10-01 07:15 UTC by b5710546232

2022-10-01 21:39 UTC, tjgurwara99 requested changes
Please provide description when contributing.

2022-10-01 21:39 UTC, tjgurwara99 commented on math/lerp.go
> +func Lerp(v0, v1, t float64) float64 {
Please provide a good documentation comment for this function. Just having a wikipedia link is not a good strategy for contributing code to projects.

2022-10-02 23:06 UTC, b5710546232 commented
Hi  @tjgurwara99  Thank for feedback, I have added :)

2022-10-07 11:44 UTC, tjgurwara99 approved these changes

2022-10-07 11:50 UTC, raklaptudirm approved these changes

2022-10-07 11:50 UTC, merged