Rsa fuzz
TheAlgorithms/Go pull request #591
Opened 2022-10-24 06:32 UTC by mcaci

Hi, in the context of #480 I'm adding the fuzz tests for the rsa algorithm. I tested it with go test ./cipher/rsa/ to test the corpus and go test -fuzz=FuzzRsa ./cipher/rsa/ to run the fuzzer itself.
If that Is that ok for you to add it let me know. Also if you have any feedbacks about my change let me know so that I can adapt it.
Thanks!

2022-10-25 14:00 UTC, tjgurwara99 requested changes

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
>  	q := int64(53)
```suggestion
func testPrecondition(t *testing.T) (int64, int64, int64) {
	t.Helper()
	// Both prime numbers
	p := int64(61)
	q := int64(53)
```
mark this as a helper function. That way you won't have to add "Algorithm failed in preamble stage" everytime an error happens.

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
>  		t.Fatal("Algorithm failed in preamble stage:\n\tPrime numbers are chosen statically and it shouldn't fail at this stage")
```suggestion
		t.Fatal("something went wrong: prime numbers are chosen statically and it shouldn't fail at this stage")
```

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
>  		t.Fatal("Algorithm failed in preamble stage:\n\tPrime numbers are chosen statically and it shouldn't fail at this stage")
Not that big a difference but a meaningful one - the Go test output shouldn't have newlines and/or tabs (not something you did but if you can change it 🙏🏼)

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
>  		t.Fatalf("Algorithm failed in preamble stage:\n\tProblem with a modular directory dependency: %v", err)
```suggestion
		t.Fatalf("something went wrong: problem with %q: %v", "modular.Inverse", err)
```

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
> +			t.Fatalf("Failed to Encrypt test string:\n\tErrMessage: %v", err)
```suggestion
			t.Fatalf("failed to encrypt string: %v", err)
```

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
> +			t.Fatalf("Failed to Decrypt test string:\n\tErrMessage: %v", err)
```suggestion
			t.Fatalf("failed to decrypt string: %v", err)
```

2022-10-25 14:00 UTC, tjgurwara99 commented on cipher/rsa/rsa_test.go
> +				input, input, decrypted)
```suggestion
			t.Fatalf("expected: %q, got: %q", input, decrypted)
```

2022-10-25 18:43 UTC, mcaci commented
Hi @tjgurwara99, I pushed all the changes you suggested me, thanks for all your feedbacks, especially the `t.Helper()` I have just learned about it. Let me know if you have other feedbacks and if I properly addressed the comments from the conversations you shared with me. Thanks again!

2022-10-30 16:37 UTC, tjgurwara99 approved these changes

2022-10-31 16:43 UTC, raklaptudirm approved these changes

2022-10-31 16:43 UTC, merged