add: implement sum of digits algorithm
TheAlgorithms/Go pull request #597
Opened 2022-10-29 12:56 UTC by kalyan-arepalle

Implement sum of digits algorithm to fetch sum of digits of an integer.

2022-10-30 16:30 UTC, tjgurwara99 requested changes

2022-10-30 16:30 UTC, tjgurwara99 commented on math/sum_of_digits.go
> +func SumOfDigits(num int64) (sum int64) {
```suggestion
func SumOfDigits[T constraints.Integer](num T) (sum T) {
```

This applies to all `Integers` not just `int64` 😄

2022-10-30 16:30 UTC, tjgurwara99 commented on math/sum_of_digits.go
> +	}
This would need more thinking to apply to the generic version of this.

2022-11-18 17:44 UTC, kalyan-arepalle commented
Apologies not able to pick this up, will raise another pr when time permits

2022-11-18 17:44 UTC, closed without merging