fix: misspelled variable
TheAlgorithms/Go pull request #618
Opened 2023-01-30 17:15 UTC by partylikeits1983

Fix incorrectly spelled variable name "halfHumber" to "halfNumber".

2023-01-30 17:37 UTC, tjgurwara99 requested changes

2023-01-30 17:37 UTC, tjgurwara99 commented on math/binary/sqrt.go
>  }
```suggestion
func Sqrt(n float32) float32 {
	var half, y float32
	half = n * 0.5
	z := math.Float32bits(n)
	z = 0x5f3759df - (z >> 1) // floating point bit level hacking
	y = math.Float32frombits(z)
	y = y * (threeHalves - (half * y * y)) // Newton's approximation
	return 1 / y
}
```

I think the context makes it clear so you can actually remove the `Number` from the name there 😄

2023-01-30 17:55 UTC, siriak approved these changes
Looks good, thanks!

2023-01-30 18:41 UTC, raklaptudirm submitted a review, later dismissed

2023-01-31 09:21 UTC, yanglbme approved these changes

2023-01-31 16:31 UTC, tjgurwara99 approved these changes

2023-01-31 16:34 UTC, merged