refactor: refactor comments and variable declaration compliant with godoc
TheAlgorithms/Go pull request #667
Opened 2023-10-04 05:27 UTC by himanshu-patel-dev

2023-10-04 10:47 UTC, tjgurwara99 submitted a review, later dismissed

2023-10-05 09:58 UTC, raklaptudirm requested changes

2023-10-05 09:58 UTC, raklaptudirm commented on graph/topological.go
> +// Topological Assumes that graph given is valid and possible to
```suggestion
// Topological assumes that graph given is valid and that its possible to
```

2023-10-06 15:42 UTC, tjgurwara99 approved these changes

2023-10-06 16:50 UTC, raklaptudirm approved these changes

2023-10-06 16:52 UTC, merged