Stack
TheAlgorithms/Go pull request #74
Opened 2019-10-26 20:47 UTC by george-e-shaw-iv

* Implemented the stack data structure.

2020-07-06 15:28 UTC, brayo-pip commented
@cclauss this is more ur domain

2020-10-17 14:50 UTC, Mystigan requested changes
- Keep the stack type unexported and add an exported func `InitStack` or `New` to initialize an empty stack. This would ensure that a user can import and use this library, at the same time not modify the stack instance directly.
- Add some tests.

2020-10-17 14:50 UTC, Mystigan commented on data-structures/stack/stack.go
> +type Stack struct {
Why enclose it in a struct?
You could try something like `type Stack []interface{}`

2021-09-10 21:11 UTC, tjgurwara99 commented
Please take a look at our new [contribution guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

2021-09-24 06:00 UTC, closed without merging