Added paypal and gitter badges
TheAlgorithms/Go pull request #89
Opened 2019-10-31 20:06 UTC by LarryBattle

Added paypal and gitter badges because that's what the other repos have. :-)

https://github.com/TheAlgorithms/Python/blob/master/README.md
https://github.com/TheAlgorithms/Rust/blob/master/README.md

2021-09-10 21:22 UTC, Panquesito7 requested changes

2021-09-10 21:22 UTC, Panquesito7 commented on README.md
> +[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/TheAlgorithms/100) &nbsp;
We use [**Liberapay**](https://liberapay.com/TheAlgorithms) now. You may want to change it. 🙂
```suggestion
[![Income](https://img.shields.io/liberapay/receives/TheAlgorithms.svg?logo=liberapay)](https://liberapay.com/TheAlgorithms) &nbsp;
```

2021-09-10 21:22 UTC, Panquesito7 commented on README.md
> +[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/TheAlgorithms) &nbsp;
Gitter is not really being used, so you may want to add a Discord badge, too.
```suggestion
[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/TheAlgorithms) &nbsp;
[![Discord chat](https://img.shields.io/discord/808045925556682782.svg?logo=discord&colorB=7289DA)](https://discord.gg/c7MnfGFGa6)
```

2021-09-11 03:52 UTC, raklaptudirm commented
Resolve the problems and re-request review please.

2021-09-11 11:23 UTC, tjgurwara99 requested changes
Please make the changes requested by @Panquesito7. There have been some changes in the README.md file in the master branch. Could you pull our master branch code and resolve any conflicts that arise.

2021-09-13 06:38 UTC, LarryBattle commented
Hey guys, sorry but I can't contribute to open source projects without getting approval from my employer :-( Closing for now.

2021-09-13 06:38 UTC, closed without merging

2021-09-13 07:33 UTC, raklaptudirm commented
What, how is that a thing?